server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hoty836/configrepo
          username: hoty836
          password: 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
          force-pull: true
          timeout: 30